# importing pandas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import streamlit as st

@st.cache_resource
def buildModel():
        # -*- coding: utf-8 -*-
    """cloud_computing_module02.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1C0ygbItzu3l0sl2T1h9RtLMX0kFkxsTc
    """
    """Next we need to read the train.csv data that we dropped here. With head() we are given the first 5 results."""

    df = pd.read_csv('train.csv', encoding='ISO-8859-1')
    df.head()

    """Next let's check if the data has null-values, which could cause problems later. We see that there is a couple: one in text-column and one on selected_text."""

    df.isnull().sum()

    """Let's remove those nulls."""

    # inplace means this will replace the values in the same data table,
    # which means we don't need to save it to a new variable
    df.dropna(inplace=True)

    # let's check again if there a re nulls with the code snippet above.
    # Results: Zero nulls.

    """With describe we can see some basic data, like a mean value of the columns.

    This seems to display only the strictly numeric values (which excludes the age gap column): population, land area and density.
    """

    df.describe()

    """# Training
    I think I should choose the columns for  *text* and *sentiment* for this. I should train the model with the *text* and compare the results with *sentiment* to see if the training went well. This means that the results for each text should correspond with the sentiment.

    I chose to split the data so that 75% is used for training and 25% for testing. If I understood correctly, the random_state is a random value that will make sure the split is reproducible while being random.
    """



    # this seperates the columns from the original dataframe to seperate variables
    text = df['text']
    sentiment = df['sentiment']

    text_train, text_test, sentiment_train, sentiment_test = train_test_split(text, sentiment, test_size=0.25, random_state=39)

    """Next we will actually train the model. This will vectorize and classify the data using packages from the sklearn import.

    The Pipeline is an optional helper tool to run several steps in one coherent step.

    The TfidfVectorizer does the vectorizing and the LinearSVC does the classification (linear)

    Then we fit the data which basically is the training itself
    """

    text_classifier = Pipeline([
        ('vectorizing', TfidfVectorizer()),
        ('classification', LinearSVC())
    ])


    text_classifier.fit(text_train, sentiment_train)

    """# Testing the model
    We test this model by using the testing part of the data (the 25%) and compare it to the results the model gives us.
    """
    # predictions = text_classifier.predict(text_test)

    # print(classification_report(sentiment_test, predictions))

       # returning the model
    return text_classifier
